version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: mastermind-apache
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    restart: unless-stopped
    ports:
      - "59111:80"
